### ISSUE TITLE
Oven Light Presented as Select Entity instead of Light?

### ISSUE THREAD

**Issue by peoute** [simbaja/ha_gehome#239]
I installed this through HACS easily and it seemed to pull in the entities and allow the control I expected.

However, the oven light is presented as "select" with two options: "Off" and "High" . . . Is there any way to present it as a light natively that can toggle on and off?

If there's a reason it has to be a select, what's the best option to mask that in HA and get the toggling behavior when interacting with it?

ha_gehome v0.6.10

Device info
PHS930YP1FS
by GE
Firmware: Appliance=2.0.28.147/Wifi=0.2.5.122

![Screenshot 2024-03-24 at 11 56 47 PM](https://github.com/simbaja/ha_gehome/assets/7222044/726e9f7a-99f6-4eec-a036-1cec73d95d15)

**Comment by adamherbert** [comment]
I created a template entity for that:
```
light:
  - platform: template
    lights:
      oven_light:
        value_template: >-
          {%- if is_state("select.oven_light", "High") -%}
          On
          {%- else -%}
          Off
          {%- endif -%}
        turn_on:
          service: select.select_option
          target:
            entity_id: select.oven_light
          data:
            option: "High"
        turn_off:
          service: select.select_option
          target:
            entity_id: select.oven_light
          data:
            option: "Off"
```
